name: Test

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*'
      - 'Cargo.toml'
  push:
    branches: [master]

jobs:
  clippy:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - uses: Swatinem/rust-cache@v2

      - name: Run unit test
        run: |
          cargo test \
            --all-targets \
            --all-features \
            --no-fail-fast
